name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/cache@v2
        with:
          # I know it's no recommened to cache node_modules, but I want faster
          # build.
          path: ~/.npm
          key: modules-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            modules-cache

      - name: Build and push to gh-pages branch
        run: |

          git config --global user.name 'CI bot'
          git config --global user.email 'letientai299@bot.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          git checkout gh-pages --force
          find . -type d | grep -v '.git' | grep -vE '^\.$' | xargs rm -rf

          git checkout master .

          # if node_modules exists in cache, copy them back to main workspace
          [ -d ~/.npm/node_modules ] && mv ~/.npm/node_modules .
          npm install --silent
          make all

          # render interview contents
          cd interview
          make render
          rm -rf public templates src scripts .gitignore
          mv ./dist/* .
          cd ..

          # done with node_modules, move them to cache location
          mv node_modules ~/.npm/node_modules

          echo
          echo "Remove every thing non-web"
          find . -type d | grep 'node_modules' | xargs rm -rf
          find . -type f | grep 'tpl' | xargs rm -rf
          find . -type f | grep -vE '.git/' | grep -vE '\.(json|html|css|js|png|jpg|webp|woff2?|ttf|svg|eot)$' | xargs rm

          git add .

          git commit -m "Generate index.html from ${GITHUB_SHA}" --allow-empty
          git push --force

